version: "3"

services:
  appserver:
    build: ./server/.
    image: helloworldapp:latest
    restart: always
    expose: 
      - 5050
    environment:
        APP_PORT: 5050
    container_name: helloworld-app
  webserver:  
    build: 
      context: ./client/
      dockerfile: Dockerfile
      args:
        - deployenv=prod
        - appserverurl=helloworld-app
        - appserverport=5050
    image: helloworldweb:latest
    expose: 
      - 80
    restart: always
    container_name: helloworld-web
    environment:
      VIRTUAL_HOST: dockertest.ankur.com
    links:
      - appserver:appserver
networks:
  default:
    external:
      name: nginx-proxy